/**
 * quotes-data.js
 * 名人名言数据库（中英文，约400条）
 * 每条包含：quote(名言), author(作者), source(出处), theme(主题)
 */

module.exports = [
  // ===== 励志与坚持 =====
  { quote: "天行健，君子以自强不息。", author: "《周易》", source: "易经", theme: "励志" },
  { quote: "有志者，事竟成，破釜沉舟，百二秦关终属楚。", author: "蒲松龄", source: "自勉联", theme: "励志" },
  { quote: "苦心人，天不负，卧薪尝胆，三千越甲可吞吴。", author: "蒲松龄", source: "自勉联", theme: "励志" },
  { quote: "锲而不舍，金石可镂。", author: "荀子", source: "《劝学》", theme: "励志" },
  { quote: "业精于勤，荒于嬉；行成于思，毁于随。", author: "韩愈", source: "《进学解》", theme: "励志" },
  { quote: "千淘万漉虽辛苦，吹尽狂沙始到金。", author: "刘禹锡", source: "《浪淘沙》", theme: "励志" },
  { quote: "长风破浪会有时，直挂云帆济沧海。", author: "李白", source: "《行路难》", theme: "励志" },
  { quote: "会当凌绝顶，一览众山小。", author: "杜甫", source: "《望岳》", theme: "励志" },
  { quote: "不积跬步，无以至千里；不积小流，无以成江海。", author: "荀子", source: "《劝学》", theme: "励志" },
  { quote: "宝剑锋从磨砺出，梅花香自苦寒来。", author: "冯梦龙", source: "《警世通言》", theme: "励志" },
  { quote: "只要功夫深，铁杵磨成针。", author: "李白", source: "民间传说", theme: "励志" },
  { quote: "古之立大事者，不惟有超世之才，亦必有坚忍不拔之志。", author: "苏轼", source: "《晁错论》", theme: "励志" },
  { quote: "生于忧患，死于安乐。", author: "孟子", source: "《孟子》", theme: "励志" },
  { quote: "天将降大任于斯人也，必先苦其心志，劳其筋骨。", author: "孟子", source: "《孟子》", theme: "励志" },
  { quote: "路漫漫其修远兮，吾将上下而求索。", author: "屈原", source: "《离骚》", theme: "励志" },
  { quote: "壮志饥餐胡虏肉，笑谈渴饮匈奴血。", author: "岳飞", source: "《满江红》", theme: "励志" },
  { quote: "三十功名尘与土，八千里路云和月。", author: "岳飞", source: "《满江红》", theme: "励志" },
  { quote: "莫等闲，白了少年头，空悲切。", author: "岳飞", source: "《满江红》", theme: "励志" },
  { quote: "人生自古谁无死，留取丹心照汗青。", author: "文天祥", source: "《过零丁洋》", theme: "励志" },
  { quote: "粉骨碎身浑不怕，要留清白在人间。", author: "于谦", source: "《石灰吟》", theme: "励志" },
  { quote: "千磨万击还坚劲，任尔东西南北风。", author: "郑燮", source: "《竹石》", theme: "励志" },
  { quote: "落红不是无情物，化作春泥更护花。", author: "龚自珍", source: "《己亥杂诗》", theme: "励志" },
  { quote: "我自横刀向天笑，去留肝胆两昆仑。", author: "谭嗣同", source: "狱中题壁", theme: "励志" },
  { quote: "为有牺牲多壮志，敢教日月换新天。", author: "毛泽东", source: "《七律·到韶山》", theme: "励志" },
  { quote: "数风流人物，还看今朝。", author: "毛泽东", source: "《沁园春·雪》", theme: "励志" },
  { quote: "世上无难事，只要肯登攀。", author: "毛泽东", source: "《水调歌头》", theme: "励志" },
  { quote: "自信人生二百年，会当水击三千里。", author: "毛泽东", source: "《七古》", theme: "励志" },
  { quote: "一万年太久，只争朝夕。", author: "毛泽东", source: "《满江红》", theme: "励志" },
  { quote: "雄关漫道真如铁，而今迈步从头越。", author: "毛泽东", source: "《忆秦娥》", theme: "励志" },
  { quote: "今日长缨在手，何时缚住苍龙？", author: "毛泽东", source: "《清平乐》", theme: "励志" },
  { quote: "不到长城非好汉，屈指行程二万。", author: "毛泽东", source: "《清平乐》", theme: "励志" },
  { quote: "为中华之崛起而读书。", author: "周恩来", source: "少年立志", theme: "励志" },
  { quote: "面壁十年图破壁，难酬蹈海亦英雄。", author: "周恩来", source: "《大江歌罢》", theme: "励志" },
  { quote: "愿相会于中华腾飞世界时。", author: "周恩来", source: "少年立志", theme: "励志" },
  { quote: "愿少年乘风破浪，他日毋忘化雨功。", author: "汪曾祺", source: "自勉", theme: "励志" },
  { quote: "少年易老学难成，一寸光阴不可轻。", author: "朱熹", source: "《偶成》", theme: "励志" },
  { quote: "纸上得来终觉浅，绝知此事要躬行。", author: "陆游", source: "《冬夜读书示子聿》", theme: "励志" },
  { quote: "少壮不努力，老大徒伤悲。", author: "汉乐府", source: "《长歌行》", theme: "励志" },
  { quote: "盛年不重来，一日难再晨。及时当勉励，岁月不待人。", author: "陶渊明", source: "《杂诗》", theme: "励志" },
  { quote: "老骥伏枥，志在千里；烈士暮年，壮心不已。", author: "曹操", source: "《龟虽寿》", theme: "励志" },
  { quote: "捐躯赴国难，视死忽如归。", author: "曹植", source: "《白马篇》", theme: "励志" },
  { quote: "刑天舞干戚，猛志固常在。", author: "陶渊明", source: "《读山海经》", theme: "励志" },
  { quote: "时人错把比严光，我自横眠向竹篱。", author: "陆游", source: "《自嘲》", theme: "励志" },
  { quote: "壮心未与年俱老，死去犹能作鬼雄。", author: "陆游", source: "《书愤》", theme: "励志" },
  { quote: "王师北定中原日，家祭无忘告乃翁。", author: "陆游", source: "《示儿》", theme: "励志" },
  { quote: "僵卧孤村不自哀，尚思为国戍轮台。", author: "陆游", source: "《十一月四日风雨大作》", theme: "励志" },
  { quote: "出师未捷身先死，长使英雄泪满襟。", author: "杜甫", source: "《蜀相》", theme: "励志" },
  { quote: "安得广厦千万间，大庇天下寒士俱欢颜。", author: "杜甫", source: "《茅屋为秋风所破歌》", theme: "励志" },
  { quote: "生当作人杰，死亦为鬼雄。", author: "李清照", source: "《夏日绝句》", theme: "励志" },
  { quote: "醉里挑灯看剑，梦回吹角连营。", author: "辛弃疾", source: "《破阵子》", theme: "励志" },
  { quote: "了却君王天下事，赢得生前身后名。可怜白发生！", author: "辛弃疾", source: "《破阵子》", theme: "励志" },
  { quote: "想当年，金戈铁马，气吞万里如虎。", author: "辛弃疾", source: "《永遇乐》", theme: "励志" },
  { quote: "凭谁问：廉颇老矣，尚能饭否？", author: "辛弃疾", source: "《永遇乐》", theme: "励志" },
  { quote: "青山遮不住，毕竟东流去。", author: "辛弃疾", source: "《菩萨蛮》", theme: "励志" },
  { quote: "天下英雄谁敌手？曹刘。生子当如孙仲谋。", author: "辛弃疾", source: "《南乡子》", theme: "励志" },

  // ===== 智慧与处世 =====
  { quote: "知人者智，自知者明。", author: "老子", source: "《道德经》", theme: "智慧" },
  { quote: "胜人者有力，自胜者强。", author: "老子", source: "《道德经》", theme: "智慧" },
  { quote: "祸兮，福之所倚；福兮，祸之所伏。", author: "老子", source: "《道德经》", theme: "智慧" },
  { quote: "上善若水，水善利万物而不争。", author: "老子", source: "《道德经》", theme: "智慧" },
  { quote: "以其不争，故天下莫能与之争。", author: "老子", source: "《道德经》", theme: "智慧" },
  { quote: "合抱之木，生于毫末；九层之台，起于累土。", author: "老子", source: "《道德经》", theme: "智慧" },
  { quote: "信言不美，美言不信。", author: "老子", source: "《道德经》", theme: "智慧" },
  { quote: "学而不思则罔，思而不学则殆。", author: "孔子", source: "《论语》", theme: "智慧" },
  { quote: "己所不欲，勿施于人。", author: "孔子", source: "《论语》", theme: "智慧" },
  { quote: "三人行，必有我师焉。择其善者而从之，其不善者而改之。", author: "孔子", source: "《论语》", theme: "智慧" },
  { quote: "君子坦荡荡，小人长戚戚。", author: "孔子", source: "《论语》", theme: "智慧" },
  { quote: "知之为知之，不知为不知，是知也。", author: "孔子", source: "《论语》", theme: "智慧" },
  { quote: "逝者如斯夫，不舍昼夜。", author: "孔子", source: "《论语》", theme: "智慧" },
  { quote: "见贤思齐焉，见不贤而内自省也。", author: "孔子", source: "《论语》", theme: "智慧" },
  { quote: "君子和而不同，小人同而不和。", author: "孔子", source: "《论语》", theme: "智慧" },
  { quote: "工欲善其事，必先利其器。", author: "孔子", source: "《论语》", theme: "智慧" },
  { quote: "欲速则不达，见小利则大事不成。", author: "孔子", source: "《论语》", theme: "智慧" },
  { quote: "不患无位，患所以立。不患莫己知，求为可知也。", author: "孔子", source: "《论语》", theme: "智慧" },
  { quote: "君子求诸己，小人求诸人。", author: "孔子", source: "《论语》", theme: "智慧" },
  { quote: "水至清则无鱼，人至察则无徒。", author: "孔子", source: "《大戴礼记》", theme: "智慧" },
  { quote: "兼听则明，偏信则暗。", author: "魏徵", source: "《资治通鉴》", theme: "智慧" },
  { quote: "以铜为镜，可以正衣冠；以史为镜，可以知兴替；以人为镜，可以明得失。", author: "李世民", source: "《旧唐书》", theme: "智慧" },
  { quote: "水能载舟，亦能覆舟。", author: "魏徵", source: "《贞观政要》", theme: "智慧" },
  { quote: "前事不忘，后事之师。", author: "刘向", source: "《战国策》", theme: "智慧" },
  { quote: "智者千虑，必有一失；愚者千虑，必有一得。", author: "司马迁", source: "《史记》", theme: "智慧" },
  { quote: "非淡泊无以明志，非宁静无以致远。", author: "诸葛亮", source: "《诫子书》", theme: "智慧" },
  { quote: "勿以恶小而为之，勿以善小而不为。", author: "刘备", source: "《三国志》", theme: "智慧" },
  { quote: "良药苦于利于病，忠言逆于利于行。", author: "韩婴", source: "《韩诗外传》", theme: "智慧" },
  { quote: "泰山不让土壤，故能成其大；河海不择细流，故能就其深。", author: "李斯", source: "《谏逐客书》", theme: "智慧" },
  { quote: "一寸光阴一寸金，寸金难买寸光阴。", author: "王贞白", source: "《白鹿洞》", theme: "智慧" },
  { quote: "问渠那得清如许，为有源头活水来。", author: "朱熹", source: "《观书有感》", theme: "智慧" },
  { quote: "不识庐山真面目，只缘身在此山中。", author: "苏轼", source: "《题西林壁》", theme: "智慧" },
  { quote: "人有冲天之志，非运不能自通。", author: "吕蒙正", source: "《寒窑赋》", theme: "智慧" },
  { quote: "当局者迷，旁观者清。", author: "沈括", source: "《梦溪笔谈》", theme: "智慧" },
  { quote: "人有逆天之时，天无绝人之路。", author: "冯梦龙", source: "《醒世恒言》", theme: "智慧" },
  { quote: "世事洞明皆学问，人情练达即文章。", author: "曹雪芹", source: "《红楼梦》", theme: "智慧" },
  { quote: "身后有余忘缩手，眼前无路想回头。", author: "曹雪芹", source: "《红楼梦》", theme: "智慧" },
  { quote: "机关算尽太聪明，反算了卿卿性命。", author: "曹雪芹", source: "《红楼梦》", theme: "智慧" },
  { quote: "假作真时真亦假，无为有处有还无。", author: "曹雪芹", source: "《红楼梦》", theme: "智慧" },
  { quote: "守得贫寒耐得富，久在芝兰室自香。", author: "吕坤", source: "《呻吟语》", theme: "智慧" },
  { quote: "大事难事看担当，逆境顺境看襟度。", author: "吕坤", source: "《呻吟语》", theme: "智慧" },
  { quote: "无一例而不行，无一私而可徇。", author: "朱熹", source: "《白鹿洞书院学规》", theme: "智慧" },

  // ===== 心态与豁达 =====
  { quote: "宠辱不惊，闲看庭前花开花落；去留无意，漫随天外云卷云舒。", author: "陈继儒", source: "《小窗幽记》", theme: "豁达" },
  { quote: "是非成败转头空，青山依旧在，几度夕阳红。", author: "杨慎", source: "《临江仙》", theme: "豁达" },
  { quote: "竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。", author: "苏轼", source: "《定风波》", theme: "豁达" },
  { quote: "回首向来萧瑟处，归去，也无风雨也无晴。", author: "苏轼", source: "《定风波》", theme: "豁达" },
  { quote: "人生如逆旅，我亦是行人。", author: "苏轼", source: "《临江仙》", theme: "豁达" },
  { quote: "不以物喜，不以己悲。", author: "范仲淹", source: "《岳阳楼记》", theme: "豁达" },
  { quote: "先天下之忧而忧，后天下之乐而乐。", author: "范仲淹", source: "《岳阳楼记》", theme: "豁达" },
  { quote: "牢骚太盛防肠断，风物长宜放眼量。", author: "毛泽东", source: "《七律》", theme: "豁达" },
  { quote: "不管风吹浪打，胜似闲庭信步。", author: "毛泽东", source: "《水调歌头》", theme: "豁达" },
  { quote: "敌军围困万千重，我自岿然不动。", author: "毛泽东", source: "《西江月》", theme: "豁达" },
  { quote: "踏遍青山人未老，风景这边独好。", author: "毛泽东", source: "《清平乐》", theme: "豁达" },
  { quote: "春风得意马蹄疾，一日看尽长安花。", author: "孟郊", source: "《登科后》", theme: "豁达" },
  { quote: "采菊东篱下，悠然见南山。", author: "陶渊明", source: "《饮酒》", theme: "豁达" },
  { quote: "久在樊笼里，复得返自然。", author: "陶渊明", source: "《归园田居》", theme: "豁达" },
  { quote: "山重水复疑无路，柳暗花明又一村。", author: "陆游", source: "《游山西村》", theme: "豁达" },
  { quote: "沉舟侧畔千帆过，病树前头万木春。", author: "刘禹锡", source: "《酬乐天》", theme: "豁达" },
  { quote: "莫愁前路无知己，天下谁人不识君。", author: "高适", source: "《别董大》", theme: "豁达" },
  { quote: "海内存知己，天涯若比邻。", author: "王勃", source: "《送杜少府》", theme: "豁达" },
  { quote: "两岸猿声啼不住，轻舟已过万重山。", author: "李白", source: "《早发白帝城》", theme: "豁达" },
  { quote: "人生得意须尽欢，莫使金樽空对月。", author: "李白", source: "《将进酒》", theme: "豁达" },
  { quote: "天生我材必有用，千金散尽还复来。", author: "李白", source: "《将进酒》", theme: "豁达" },
  { quote: "仰天大笑出门去，我辈岂是蓬蒿人。", author: "李白", source: "《南陵别儿童》", theme: "豁达" },
  { quote: "安能摧眉折腰事权贵，使我不得开心颜。", author: "李白", source: "《梦游天姥吟留别》", theme: "豁达" },
  { quote: "人生在世不称意，明朝散发弄扁舟。", author: "李白", source: "《宣州谢朓楼》", theme: "豁达" },
  { quote: "事了拂衣去，深藏身与名。", author: "李白", source: "《侠客行》", theme: "豁达" },
  { quote: "大漠孤烟直，长河落日圆。", author: "王维", source: "《使至塞上》", theme: "豁达" },
  { quote: "行到水穷处，坐看云起时。", author: "王维", source: "《终南别业》", theme: "豁达" },
  { quote: "明月松间照，清泉石上流。", author: "王维", source: "《山居秋暝》", theme: "豁达" },
  { quote: "正是江南好风景，落花时节又逢君。", author: "杜甫", source: "《江南逢李龟年》", theme: "豁达" },
  { quote: "无边落木萧萧下，不尽长江滚滚来。", author: "杜甫", source: "《登高》", theme: "豁达" },
  { quote: "星垂平野阔，月涌大江流。", author: "杜甫", source: "《旅夜书怀》", theme: "豁达" },
  { quote: "随风潜入夜，润物细无声。", author: "杜甫", source: "《春夜喜雨》", theme: "豁达" },
  { quote: "两个黄鹂鸣翠柳，一行白鹭上青天。", author: "杜甫", source: "《绝句》", theme: "豁达" },
  { quote: "但愿人长久，千里共婵娟。", author: "苏轼", source: "《水调歌头》", theme: "豁达" },
  { quote: "人有悲欢离合，月有阴晴圆缺，此事古难全。", author: "苏轼", source: "《水调歌头》", theme: "豁达" },
  { quote: "人生到处知何似，应似飞鸿踏雪泥。", author: "苏轼", source: "《和子由渑池怀旧》", theme: "豁达" },
  { quote: "休对故人思故国，且将新火试新茶。诗酒趁年华。", author: "苏轼", source: "《望江南》", theme: "豁达" },
  { quote: "谁道人生无再少？门前流水尚能西！", author: "苏轼", source: "《浣溪沙》", theme: "豁达" },
  { quote: "人生如梦，一尊还酹江月。", author: "苏轼", source: "《念奴娇》", theme: "豁达" },
  { quote: "大江东去，浪淘尽，千古风流人物。", author: "苏轼", source: "《念奴娇》", theme: "豁达" },
  { quote: "十年生死两茫茫，不思量，自难忘。", author: "苏轼", source: "《江城子》", theme: "豁达" },
  { quote: "纵有千年铁门槛，终须一个土馒头。", author: "范成大", source: "《重九日行营》", theme: "豁达" },
  { quote: "问君能有几多愁？恰似一江春水向东流。", author: "李煜", source: "《虞美人》", theme: "豁达" },
  { quote: "今人不见古时月，今月曾经照古人。", author: "李白", source: "《把酒问月》", theme: "豁达" },
  { quote: "浮云游子意，落日故人情。", author: "李白", source: "《送友人》", theme: "豁达" },
  { quote: "抽刀断水水更流，举杯消愁愁更愁。", author: "李白", source: "《宣州谢朓楼》", theme: "豁达" },
  { quote: "两情若是久长时，又岂在朝朝暮暮。", author: "秦观", source: "《鹊桥仙》", theme: "豁达" },
  { quote: "曾经沧海难为水，除却巫山不是云。", author: "元稹", source: "《离思》", theme: "豁达" },
  { quote: "人生代代无穷已，江月年年望相似。", author: "张若虚", source: "《春江花月夜》", theme: "豁达" },
  { quote: "年年岁岁花相似，岁岁年年人不同。", author: "刘希夷", source: "《代悲白头翁》", theme: "豁达" },
  { quote: "年年柳色，灞陵伤别。", author: "李白", source: "《忆秦娥》", theme: "豁达" },

  // ===== 爱与情感 =====
  { quote: "执子之手，与子偕老。", author: "《诗经》", source: "《邶风·击鼓》", theme: "爱情" },
  { quote: "愿得一心人，白头不相离。", author: "卓文君", source: "《白头吟》", theme: "爱情" },
  { quote: "身无彩凤双飞翼，心有灵犀一点通。", author: "李商隐", source: "《无题》", theme: "爱情" },
  { quote: "春蚕到死丝方尽，蜡炬成灰泪始干。", author: "李商隐", source: "《无题》", theme: "爱情" },
  { quote: "此情可待成追忆，只是当时已惘然。", author: "李商隐", source: "《锦瑟》", theme: "爱情" },
  { quote: "在天愿作比翼鸟，在地愿为连理枝。", author: "白居易", source: "《长恨歌》", theme: "爱情" },
  { quote: "天长地久有时尽，此恨绵绵无绝期。", author: "白居易", source: "《长恨歌》", theme: "爱情" },
  { quote: "衣带渐宽终不悔，为伊消得人憔悴。", author: "柳永", source: "《蝶恋花》", theme: "爱情" },
  { quote: "众里寻他千百度，蓦然回首，那人却在灯火阑珊处。", author: "辛弃疾", source: "《青玉案》", theme: "爱情" },
  { quote: "问世间，情为何物，直教生死相许。", author: "元好问", source: "《摸鱼儿》", theme: "爱情" },
  { quote: "愿君多采撷，此物最相思。", author: "王维", source: "《相思》", theme: "爱情" },
  { quote: "独在异乡为异客，每逢佳节倍思亲。", author: "王维", source: "《九月九日》", theme: "爱情" },
  { quote: "取次花丛懒回顾，半缘修道半缘君。", author: "元稹", source: "《离思》", theme: "爱情" },

  // ===== 外国名言·英文 =====
  { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs", source: "Stanford Commencement Speech 2005", theme: "励志" },
  { quote: "Stay hungry, stay foolish.", author: "Steve Jobs", source: "Stanford Commencement Speech 2005", theme: "励志" },
  { quote: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs", source: "《Jobs》biography", theme: "励志" },
  { quote: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs", source: "Stanford Commencement Speech 2005", theme: "励志" },
  { quote: "Be the change you wish to see in the world.", author: "Mahatma Gandhi", source: "Attributed", theme: "励志" },
  { quote: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi", source: "Attributed", theme: "励志" },
  { quote: "The future depends on what you do today.", author: "Mahatma Gandhi", source: "Attributed", theme: "励志" },
  { quote: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi", source: "Attributed", theme: "励志" },
  { quote: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi", source: "Attributed", theme: "励志" },
  { quote: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama", source: "Attributed", theme: "励志" },
  { quote: "The purpose of our lives is to be happy.", author: "Dalai Lama", source: "Attributed", theme: "励志" },
  { quote: "Be kind whenever possible. It is always possible.", author: "Dalai Lama", source: "Attributed", theme: "励志" },
  { quote: "In the middle of difficulty lies opportunity.", author: "Albert Einstein", source: "Attributed", theme: "励志" },
  { quote: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein", source: "Letter to son, 1930", theme: "励志" },
  { quote: "Imagination is more important than knowledge.", author: "Albert Einstein", source: "Attributed", theme: "智慧" },
  { quote: "Try not to become a man of success. Rather become a man of value.", author: "Albert Einstein", source: "Attributed", theme: "智慧" },
  { quote: "The only source of knowledge is experience.", author: "Albert Einstein", source: "Attributed", theme: "智慧" },
  { quote: "We cannot solve our problems with the same thinking we used when we created them.", author: "Albert Einstein", source: "Attributed", theme: "智慧" },
  { quote: "The true sign of intelligence is not knowledge but imagination.", author: "Albert Einstein", source: "Attributed", theme: "智慧" },
  { quote: "It is not the strongest of the species that survives, nor the most intelligent, but the one most responsive to change.", author: "Charles Darwin", source: "Attributed (paraphrased)", theme: "智慧" },
  { quote: "The man who does not read has no advantage over the man who cannot read.", author: "Mark Twain", source: "Attributed", theme: "智慧" },
  { quote: "The secret of getting ahead is getting started.", author: "Mark Twain", source: "Attributed", theme: "励志" },
  { quote: "Kindness is the language which the deaf can hear and the blind can see.", author: "Mark Twain", source: "Attributed", theme: "智慧" },
  { quote: "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did.", author: "Mark Twain", source: "Attributed", theme: "励志" },
  { quote: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson", source: "Attributed", theme: "励志" },
  { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson", source: "Attributed", theme: "励志" },
  { quote: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson", source: "Attributed", theme: "智慧" },
  { quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson", source: "Attributed", theme: "励志" },
  { quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", source: "Speech, 1941", theme: "励志" },
  { quote: "Never give in, never give in, never, never, never, never.", author: "Winston Churchill", source: "Speech at Harrow School, 1941", theme: "励志" },
  { quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill", source: "Attributed", theme: "励志" },
  { quote: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb", source: "Proverb", theme: "励志" },
  { quote: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu", source: "《Tao Te Ching》", theme: "励志" },
  { quote: "When it is obvious that the goals cannot be reached, don't adjust the goals, adjust the action steps.", author: "Confucius", source: "Attributed", theme: "智慧" },
  { quote: "Everything has beauty, but not everyone sees it.", author: "Confucius", source: "Attributed", theme: "智慧" },
  { quote: "He who learns but does not think is lost. He who thinks but does not learn is in great danger.", author: "Confucius", source: "《Analects》", theme: "智慧" },
  { quote: "Wherever you go, go with all your heart.", author: "Confucius", source: "Attributed", theme: "智慧" },
  { quote: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius", source: "Attributed", theme: "励志" },
  { quote: "Life is really simple, but we insist on making it complicated.", author: "Confucius", source: "Attributed", theme: "智慧" },
  { quote: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison", source: "Attributed", theme: "励志" },
  { quote: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison", source: "Attributed", theme: "励志" },
  { quote: "The mind is everything. What you think you become.", author: "Buddha", source: "Attributed", theme: "智慧" },
  { quote: "Peace comes from within. Do not seek it without.", author: "Buddha", source: "Attributed", theme: "智慧" },
  { quote: "Three things cannot be long hidden: the sun, the moon, and the truth.", author: "Buddha", source: "Attributed", theme: "智慧" },
  { quote: "In the end, it's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln", source: "Attributed", theme: "励志" },
  { quote: "Whatever you are, be a good one.", author: "Abraham Lincoln", source: "Attributed", theme: "励志" },
  { quote: "The best way to predict the future is to create it.", author: "Peter Drucker", source: "Attributed", theme: "励志" },
  { quote: "Opportunity does not knock, it presents itself when you beat down the door.", author: "Kyle Chandler", source: "Attributed", theme: "励志" },
  { quote: "The only impossible journey is the one you never begin.", author: "Tony Robbins", source: "Attributed", theme: "励志" },
  { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", source: "Attributed", theme: "励志" },
  { quote: "All our dreams can come true, if we have the courage to pursue them.", author: "Walt Disney", source: "Attributed", theme: "励志" },
  { quote: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle", source: "Attributed", theme: "励志" },
  { quote: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", source: "《Nicomachean Ethics》", theme: "智慧" },
  { quote: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle", source: "Attributed", theme: "励志" },
  { quote: "Happiness depends upon ourselves.", author: "Aristotle", source: "Attributed", theme: "智慧" },
  { quote: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle", source: "Attributed", theme: "智慧" },
  { quote: "It is not enough to have a good mind; the main thing is to use it well.", author: "Rene Descartes", source: "Attributed", theme: "智慧" },
  { quote: "I think, therefore I am.", author: "Rene Descartes", source: "《Discourse on the Method》", theme: "智慧" },
  { quote: "The unexamined life is not worth living.", author: "Socrates", source: "Attributed", theme: "智慧" },
  { quote: "The only true wisdom is in knowing you know nothing.", author: "Socrates", source: "Attributed", theme: "智慧" },
  { quote: "Be kind, for everyone you meet is fighting a hard battle.", author: "Socrates", source: "Attributed (Philo)", theme: "智慧" },
  { quote: "An unexamined life is not worth living.", author: "Socrates", source: "Plato's Apology", theme: "智慧" },
  { quote: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha", source: "Attributed", theme: "智慧" },
  { quote: "You will not be punished for your anger, you will be punished by your anger.", author: "Buddha", source: "Attributed", theme: "智慧" },
  { quote: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt", source: "Attributed", theme: "励志" },
  { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", source: "Attributed", theme: "励志" },
  { quote: "You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face.", author: "Eleanor Roosevelt", source: "Attributed", theme: "励志" },
  { quote: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington", source: "Attributed", theme: "励志" },
  { quote: "Success is getting what you want. Happiness is wanting what you get.", author: "Dale Carnegie", source: "Attributed", theme: "智慧" },
  { quote: "The most important thing in communication is hearing what isn't said.", author: "Peter Drucker", source: "Attributed", theme: "智慧" },
  { quote: "Laziness is nothing more than the habit of resting before you get tired.", author: "Jules Renard", source: "Attributed", theme: "励志" },
  { quote: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman", source: "Attributed", theme: "励志" },
  { quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela", source: "Attributed", theme: "励志" },
  { quote: "It always seems impossible until it's done.", author: "Nelson Mandela", source: "Attributed", theme: "励志" },
  { quote: "I learned that courage was not the absence of fear, but the triumph over it.", author: "Nelson Mandela", source: "Attributed", theme: "励志" },
  { quote: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela", source: "Speech, 1990", theme: "励志" },
  { quote: "A winner is a dreamer who never gives up.", author: "Nelson Mandela", source: "Attributed", theme: "励志" },
  { quote: "Darkness cannot drive out darkness; only light can do that.", author: "Martin Luther King Jr.", source: "Attributed", theme: "智慧" },
  { quote: "The time is always right to do what is right.", author: "Martin Luther King Jr.", source: "Attributed", theme: "智慧" },
  { quote: "Injustice anywhere is a threat to justice everywhere.", author: "Martin Luther King Jr.", source: "Letter from Birmingham Jail", theme: "智慧" },
  { quote: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr.", source: "Attributed", theme: "智慧" },
  { quote: "I have decided to stick with love. Hate is too great a burden to bear.", author: "Martin Luther King Jr.", source: "Attributed", theme: "智慧" },
  { quote: "Intelligence plus character—that is the goal of true education.", author: "Martin Luther King Jr.", source: "Attributed", theme: "智慧" },
  { quote: "Weak people revenge. Strong people forgive. Intelligent people ignore.", author: "Albert Einstein", source: "Attributed", theme: "智慧" },
  { quote: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein", source: "Attributed", theme: "智慧" },
  { quote: "The value of a man should be seen in what he gives and not in what he is able to receive.", author: "Albert Einstein", source: "Attributed", theme: "智慧" },
  { quote: "When you are courting a nice girl an hour seems like a second. When you sit on a red-hot cinder a second seems like an hour. That's relativity.", author: "Albert Einstein", source: "Attributed", theme: "智慧" },
  { quote: "If you can't explain it simply, you don't understand it well enough.", author: "Albert Einstein", source: "Attributed", theme: "智慧" },
  { quote: "Personality is to a man what perfume is to a flower.", author: "Charles Schwab", source: "Attributed", theme: "智慧" },
  { quote: "Take the first step in faith. You don't have to see the whole staircase, just take the first step.", author: "Martin Luther King Jr.", source: "Attributed", theme: "励志" },
  { quote: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky", source: "Attributed", theme: "励志" },
  { quote: "Whether you think you can or you think you can't, you are right.", author: "Henry Ford", source: "Attributed", theme: "励志" },
  { quote: "Coming together is a beginning; keeping together is progress; working together is success.", author: "Henry Ford", source: "Attributed", theme: "励志" },
  { quote: "Obstacles don't have to stop you. If you run into a wall, don't turn around and give up.", author: "Michael Jordan", source: "Attributed", theme: "励志" },
  { quote: "I can accept failure, everyone fails at something. But I can't accept not trying.", author: "Michael Jordan", source: "Attributed", theme: "励志" },
  { quote: "Failure is not fatal, but failure to change might be.", author: "John Wooden", source: "Attributed", theme: "励志" },
  { quote: "Never lie to someone who trust you. Never trust someone who lies to you.", author: "Unknown", source: "Attributed", theme: "智慧" },
  { quote: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain", source: "Attributed", theme: "智慧" },
  { quote: "Courage is not the absence of fear, but rather the judgment that something else is more important than fear.", author: "Ambrose Redmoon", source: "Attributed", theme: "励志" },
  { quote: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche", source: "《Twilight of the Idols》", theme: "智慧" },
  { quote: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche", source: "《Twilight of the Idols》", theme: "励志" },
  { quote: "Without music, life would be a mistake.", author: "Friedrich Nietzsche", source: "《Twilight of the Idols》", theme: "智慧" },
  { quote: "He who has a why to live can bear almost any how.", author: "Viktor Frankl", source: "《Man's Search for Meaning》", theme: "智慧" },
  { quote: "Everything can be taken from a man but one thing: the last of the human freedoms—to choose one's attitude.", author: "Viktor Frankl", source: "《Man's Search for Meaning》", theme: "智慧" },
  { quote: "When we are no longer able to change a situation, we are challenged to change ourselves.", author: "Viktor Frankl", source: "《Man's Search for Meaning》", theme: "智慧" },
  { quote: "It is not the strongest species that survive, nor the most intelligent, but the ones most responsive to change.", author: "Charles Darwin", source: "Attributed", theme: "智慧" },
  { quote: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde", source: "Attributed", theme: "智慧" },
  { quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde", source: "Attributed", theme: "智慧" },
  { quote: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", author: "Albert Einstein", source: "Attributed", theme: "智慧" },
  { quote: "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.", author: "Albert Einstein", source: "Attributed", theme: "智慧" },
  { quote: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain", source: "Attributed", theme: "智慧" },
  { quote: "The only completely consistent people are the dead.", author: "Aldous Huxley", source: "Attributed", theme: "智慧" },
  { quote: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde", source: "《Lady Windermere's Fan》", theme: "励志" },
  { quote: "The art of being wise is the art of knowing what to overlook.", author: "William James", source: "Attributed", theme: "智慧" },
  { quote: "Act only according to that maxim whereby you can at the same time will that it should become a universal law.", author: "Immanuel Kant", source: "《Groundwork of the Metaphysics of Morals》", theme: "智慧" },
  { quote: "Happiness is not an ideal of reason, but of imagination.", author: "Immanuel Kant", source: "Attributed", theme: "智慧" },
  { quote: "We must also think of others, for we do not live alone.", author: "Maria Montessori", source: "Attributed", theme: "智慧" },
  { quote: "Free these little children. Let them run in the fields, breathe the pure air, and grow strong and healthy.", author: "Maria Montessori", source: "Attributed", theme: "智慧" },
  { quote: "Follow your inner moonlight; don't hide the madness.", author: "Allen Ginsberg", source: "Attributed", theme: "智慧" },
  { quote: "Whoever is careless with the truth in small matters cannot be trusted with the important ones.", author: "Albert Einstein", source: "Attributed", theme: "智慧" },
  { quote: "A ship in harbor is safe, but that is not what ships are built for.", author: "John A. Shedd", source: "《Salt from My Attic》", theme: "励志" },
  { quote: "Not everything that is faced can be changed, but nothing can be changed until it is faced.", author: "James Baldwin", source: "Attributed", theme: "智慧" },
  { quote: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt", source: "First Inaugural Address, 1933", theme: "励志" },
  { quote: "Happiness is the new rich — new things to do, new places to go, and new people to love.", author: "Sophia Bush", source: "Attributed", theme: "智慧" },
  { quote: "The best revenge is massive success.", author: "Frank Sinatra", source: "Attributed", theme: "励志" },
  { quote: "Dream big and dare to fail.", author: "Norman Vaughan", source: "Attributed", theme: "励志" },
  { quote: "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.", author: "Steve Jobs", source: "Stanford Commencement Speech 2005", theme: "励志" },
  { quote: "The people who are crazy enough to think they can change the world are the ones who do.", author: "Apple Inc.", source: "Think Different campaign", theme: "励志" },
  { quote: "Stay hungry, stay foolish.", author: "Steve Jobs", source: "Stanford Commencement Speech 2005", theme: "励志" },
  { quote: "Don't let the noise of others' opinions drown out your own inner voice.", author: "Steve Jobs", source: "Stanford Commencement Speech 2005", theme: "智慧" },
  { quote: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs", source: "Stanford Commencement Speech 2005", theme: "智慧" },
  { quote: "Have the courage to follow your heart and intuition.", author: "Steve Jobs", source: "Stanford Commencement Speech 2005", theme: "智慧" },
  { quote: "Design is not just what it looks like and feels like. Design is how it works.", author: "Steve Jobs", source: "Attributed", theme: "智慧" },
  { quote: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci", source: "Attributed", theme: "智慧" },
  { quote: "The greatest risk is the risk of riskless living.", author: "Robert K. Greenleaf", source: "Attributed", theme: "励志" },
  { quote: "Leadership is not about being in charge. It is about taking care of those in your charge.", author: "Simon Sinek", source: "Attributed", theme: "智慧" },
  { quote: "People don't buy what you do, they buy why you do it.", author: "Simon Sinek", source: "《Start with Why》", theme: "智慧" },
  { quote: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupery", source: "Attributed", theme: "励志" },
  { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", source: "Attributed", theme: "励志" },
  { quote: "Life is short, and it is up to you to make it sweet.", author: "Sarah Louise Delany", source: "Attributed", theme: "智慧" },
  { quote: "You can't go back and change the beginning, but you can start where you are and change the ending.", author: "C.S. Lewis", source: "Attributed", theme: "励志" },
  { quote: "There is nothing impossible to him who will try.", author: "Alexander the Great", source: "Attributed", theme: "励志" },
  { quote: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey", source: "《7 Habits of Highly Effective People》", theme: "励志" },
  { quote: "Seek not abroad, turn back into yourself, for in the inner man dwells the truth.", author: "Saint Augustine", source: "Attributed", theme: "智慧" },
  { quote: "The soul becomes dyed with the color of its thoughts.", author: "Marcus Aurelius", source: "《Meditations》", theme: "智慧" },
  { quote: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius", source: "《Meditations》", theme: "智慧" },
  { quote: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius", source: "《Meditations》", theme: "智慧" },
  { quote: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", author: "Marcus Aurelius", source: "《Meditations》", theme: "智慧" },
  { quote: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius", source: "《Meditations》", theme: "智慧" },
  { quote: "When you arise in the morning, think of what a precious privilege it is to be alive.", author: "Marcus Aurelius", source: "《Meditations》", theme: "智慧" },
  { quote: "The obstacle is the way.", author: "Marcus Aurelius", source: "《Meditations》", theme: "励志" },
  { quote: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius", source: "《Meditations》", theme: "智慧" },
  { quote: "No one saves us but ourselves. No one can and no one may. We ourselves must walk the path.", author: "Buddha", source: "Attributed", theme: "智慧" },
  { quote: "Pain is certain, suffering is optional.", author: "Buddha", source: "Attributed", theme: "智慧" },
  { quote: "What you are is what you have been. What you will be is what you do now.", author: "Buddha", source: "Attributed", theme: "智慧" },
  { quote: "However many holy words you read, however many you speak, what good will they do you if you do not act on upon them?", author: "Buddha", source: "Attributed", theme: "智慧" },
  { quote: "In a controversy the instant we feel anger we have already ceased striving for the truth.", author: "Buddha", source: "Attributed", theme: "智慧" },
  { quote: "Rule your mind or it will rule you.", author: "Buddha", source: "Attributed", theme: "智慧" },
  { quote: "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", author: "Buddha", source: "Attributed", theme: "智慧" },
  { quote: "No one saves us but ourselves. No one can. No one may. We ourselves must walk the path.", author: "Buddha", source: "Attributed", theme: "励志" },
  { quote: "The trouble is, you think you have time.", author: "Buddha", source: "Attributed", theme: "智慧" },
  { quote: "If you light a lamp for somebody, it will also brighten your path.", author: "Buddha", source: "Attributed", theme: "智慧" },
  { quote: "Three things cannot be long hidden: the sun, the moon, the truth.", author: "Buddha", source: "Attributed", theme: "智慧" },
  { quote: "Nothing ever exists entirely alone; everything is in relation to everything else.", author: "Buddha", source: "Attributed", theme: "智慧" },
  { quote: "With our thoughts we make the world.", author: "Buddha", source: "Attributed", theme: "智慧" },
  { quote: "To understand everything is to forgive everything.", author: "Buddha", source: "Attributed", theme: "智慧" },
  { quote: "The only way to have a friend is to be one.", author: "Ralph Waldo Emerson", source: "Attributed", theme: "智慧" },
  { quote: "Love all, trust a few, do wrong to none.", author: "William Shakespeare", source: "《All's Well That Ends Well》", theme: "智慧" },
  { quote: "To thine own self be true, and it must follow, as the night the day, thou canst not then be false to any man.", author: "William Shakespeare", source: "《Hamlet》", theme: "智慧" },
  { quote: "There is nothing either good or bad, but thinking makes it so.", author: "William Shakespeare", source: "《Hamlet》", theme: "智慧" },
  { quote: "We know what we are but know not what we may be.", author: "William Shakespeare", source: "《Hamlet》", theme: "智慧" },
  { quote: "The fool doth think he is wise, but the wise man knows himself to be a fool.", author: "William Shakespeare", source: "《As You Like It》", theme: "智慧" },
  { quote: "All the world's a stage, and all the men and women merely players.", author: "William Shakespeare", source: "《As You Like It》", theme: "智慧" },
  { quote: "This above all: to thine own self be true.", author: "William Shakespeare", source: "《Hamlet》", theme: "智慧" },
  { quote: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", source: "Attributed", theme: "智慧" },
  { quote: "Patience is bitter, but its fruit is sweet.", author: "Aristotle", source: "Attributed", theme: "励志" },
  { quote: "Quality is not an act, it is a habit.", author: "Aristotle", source: "Attributed", theme: "励志" },
  { quote: "The educated differ from the uneducated as much as the living differ from the dead.", author: "Aristotle", source: "Attributed", theme: "智慧" },
  { quote: "Hope is a waking dream.", author: "Aristotle", source: "Attributed", theme: "智慧" },
  { quote: "The energy of the mind is the essence of life.", author: "Aristotle", source: "Attributed", theme: "智慧" },
  { quote: "Every act of kindness has some healing power of its own.", author: "John J. Hugh", source: "Attributed", theme: "智慧" },
  { quote: "How wonderful it is that nobody need wait a single moment before starting to improve the world.", author: "Anne Frank", source: "《Diary of a Young Girl》", theme: "励志" },
  { quote: "Think of all the beauty still left around you and be happy.", author: "Anne Frank", source: "《Diary of a Young Girl》", theme: "智慧" },
  { quote: "Whoever is happy will make others happy too.", author: "Anne Frank", source: "《Diary of a Young Girl》", theme: "智慧" },
  { quote: "The best preparation for good work tomorrow is to do good work today.", author: "Elbert Hubbard", source: "Attributed", theme: "励志" },
  { quote: "A friend is someone who knows all about you and still loves you.", author: "Elbert Hubbard", source: "Attributed", theme: "爱情" },
  { quote: "The greatest mistake you can make in life is to be continually fearing you will make one.", author: "Elbert Hubbard", source: "Attributed", theme: "励志" },
  { quote: "Art is not what you see, but what you make others see.", author: "Edgar Degas", source: "Attributed", theme: "智慧" },
  { quote: "The purpose of art is washing the dust of daily life off our souls.", author: "Pablo Picasso", source: "Attributed", theme: "智慧" },
  { quote: "Every child is an artist. The problem is how to remain an artist once we grow up.", author: "Pablo Picasso", source: "Attributed", theme: "智慧" },
  { quote: "I dream of painting and then I paint my dream.", author: "Vincent van Gogh", source: "Attributed", theme: "励志" },
  { quote: "What would life be if we had no courage to attempt anything?", author: "Vincent van Gogh", source: "Attributed", theme: "励志" },
  { quote: "If you hear a voice within you say 'you cannot paint,' then by all means paint, and that voice will be silenced.", author: "Vincent van Gogh", source: "Attributed", theme: "励志" },
  { quote: "Great things are done by a series of small things brought together.", author: "Vincent van Gogh", source: "Attributed", theme: "励志" },
  { quote: "Have no fear of perfection — you'll never reach it.", author: "Salvador Dali", source: "Attributed", theme: "智慧" },
  { quote: "Learning is not attained by chance, it must be sought for with ardor and attended to with diligence.", author: "Abigail Adams", source: "Attributed", theme: "励志" },
  { quote: "The pain of discipline is nothing like the pain of disappointment.", author: "Justin Langer", source: "Attributed", theme: "励志" },
  { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey", source: "Attributed", theme: "励志" },
  { quote: "The biggest adventure you can take is to live the life of your dreams.", author: "Oprah Winfrey", source: "Attributed", theme: "励志" },
  { quote: "If you want to achieve greatness stop asking for permission.", author: "Anonymous", source: "Attributed", theme: "励志" },
  { quote: "Don't count the days, make the days count.", author: "Muhammad Ali", source: "Attributed", theme: "励志" },
  { quote: "I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'", author: "Muhammad Ali", source: "Attributed", theme: "励志" },
  { quote: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Muhammad Ali", source: "Attributed", theme: "励志" },
  { quote: "If you always do what you have always done, you will always get what you have always gotten.", author: "Tony Robbins", source: "Attributed", theme: "励志" },
  { quote: "It's not what you do once in a while — it's what you do day in and day out that makes the difference.", author: "Jennifer Lopez", source: "Attributed", theme: "励志" },
  { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt", source: "Attributed", theme: "励志" },
  { quote: "A positive attitude causes a chain reaction of positive thoughts, events and outcomes.", author: "Wade Boggs", source: "Attributed", theme: "励志" },
  { quote: "It is not the load that breaks you down, it's the way you carry it.", author: "Lena Horne", source: "Attributed", theme: "智慧" },
  { quote: "Every day may not be good, but there is something good in every day.", author: "Alice Morse Earle", source: "Attributed", theme: "智慧" },
  { quote: "Be the energy you want to attract.", author: "Unknown", source: "Attributed", theme: "智慧" },
  { quote: "What you seek is seeking you.", author: "Rumi", source: "Attributed", theme: "智慧" },
  { quote: "The wound is the place where the Light enters you.", author: "Rumi", source: "Attributed", theme: "智慧" },
  { quote: "Let yourself be silently drawn by the strange pull of what you really love. It will not lead you astray.", author: "Rumi", source: "Attributed", theme: "智慧" },
  { quote: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", author: "Rumi", source: "Attributed", theme: "智慧" },
  { quote: "Don't grieve. Anything you lose comes round in another form.", author: "Rumi", source: "Attributed", theme: "智慧" },
  { quote: "Set your life on fire. Seek those who fan your flames.", author: "Rumi", source: "Attributed", theme: "励志" },
  { quote: "The art of knowing is knowing what to ignore.", author: "Rumi", source: "Attributed", theme: "智慧" },
  { quote: "Wherever you are, be all there.", author: "Jim Elliot", source: "Attributed", theme: "智慧" },
  { quote: "God, grant me the serenity to accept the things I cannot change, the courage to change the things I can, and the wisdom to know the difference.", author: "Reinhold Niebuhr", source: "《Serenity Prayer》", theme: "智慧" },
  { quote: "Grant me the courage to change what I can, the serenity to accept what I cannot, and the wisdom to know the difference.", author: "Reinhold Niebuhr", source: "《Serenity Prayer》", theme: "智慧" },
  { quote: "We must accept finite disappointment, but never lose infinite hope.", author: "Martin Luther King Jr.", source: "Attributed", theme: "励志" },
  { quote: "Take the first step with your hand, not a thousand miles away, but right in front of your face.", author: "Miyamoto Musashi", source: "《The Book of Five Rings》", theme: "励志" },
  { quote: "Think lightly of yourself and deeply of the world.", author: "Miyamoto Musashi", source: "《The Book of Five Rings》", theme: "智慧" },
  { quote: "There is nothing outside of yourself that can ever enable you to get better, stronger, richer, quicker, or smarter. Everything is within.", author: "Miyamoto Musashi", source: "《The Book of Five Rings》", theme: "智慧" },
  { quote: "Accept loss forever. Accept loss in your heart, and you will begin to find strength within.", author: "Miyamoto Musashi", source: "《The Book of Five Rings》", theme: "智慧" },
  { quote: "The path is the goal.", author: "Zen Proverb", source: "Proverb", theme: "智慧" },
  { quote: "When the student is ready, the teacher will appear.", author: "Buddhist Proverb", source: "Proverb", theme: "智慧" },
  { quote: "If you want to be happy, be.", author: "Leo Tolstoy", source: "Attributed", theme: "智慧" },
  { quote: "Everyone thinks of changing the world, but no one thinks of changing himself.", author: "Leo Tolstoy", source: "Attributed", theme: "智慧" },
  { quote: "All happy families are alike; each unhappy family is unhappy in its own way.", author: "Leo Tolstoy", source: "《Anna Karenina》", theme: "智慧" },
  { quote: "Be brave. Take risks. Nobody can touch you. You are the only master of your own destiny.", author: "Anita K. Booth", source: "Attributed", theme: "励志" },
  { quote: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand", source: "Attributed", theme: "励志" },
  { quote: "The person who says it cannot be done should not interrupt the person who is doing it.", author: "Chinese Proverb", source: "Proverb", theme: "励志" },
  { quote: "He who asks is a fool for five minutes, but he who does not ask remains a fool forever.", author: "Chinese Proverb", source: "Proverb", theme: "智慧" },
  { quote: "Give a man a fish and you feed him for a day. Teach him how to fish and you feed him for a lifetime.", author: "Chinese Proverb", source: "Proverb", theme: "智慧" },
  { quote: "Fall seven times, stand up eight.", author: "Japanese Proverb", source: "Proverb", theme: "励志" },
  { quote: "No matter how long the rain lasts, there will never be any true cold without hope.", author: "Dan Zadra", source: "Attributed", theme: "励志" },
  { quote: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett", source: "《The Light in the Heart》", theme: "励志" },
  { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", source: "Attributed", theme: "励志" },
  { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt", source: "Attributed", theme: "励志" },
  { quote: "It is not the critic who counts; not the man who points out how the strong man stumbled.", author: "Theodore Roosevelt", source: "《Citizenship in a Republic》", theme: "励志" },
  { quote: "Courage is not having the strength to go on; it is going on when you don't have the strength.", author: "Theodore Roosevelt", source: "Attributed", theme: "励志" },
  { quote: "Nothing in the world is worth having or worth doing unless it means effort, pain, difficulty.", author: "Theodore Roosevelt", source: "Attributed", theme: "励志" },
  { quote: "Life is what happens when you're busy making other plans.", author: "John Lennon", source: "《Beautiful Boy》", theme: "智慧" },
  { quote: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb", source: "Proverb", theme: "励志" },
  { quote: "To see what is right and not do it is the want of courage.", author: "Confucius", source: "Attributed", theme: "智慧" },
  { quote: "Better to light one small candle than to curse the darkness.", author: "Chinese Proverb", source: "Proverb", theme: "励志" },
  { quote: "He who conquers himself is the mightiest warrior.", author: "Confucius", source: "Attributed", theme: "智慧" },
  { quote: "Real knowledge is to know the extent of one's ignorance.", author: "Confucius", source: "Attributed", theme: "智慧" },
  { quote: "By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.", author: "Confucius", source: "Attributed", theme: "智慧" },
  { quote: "When you know a thing, to hold that you know it; and when you do not know a thing, to allow that you do not know it — this is knowledge.", author: "Confucius", source: "Attributed", theme: "智慧" },
  { quote: "Respect yourself and others will respect you.", author: "Confucius", source: "Attributed", theme: "智慧" },
  { quote: "The man who asks a question is a fool for a minute, the man who does not ask is a fool for life.", author: "Confucius", source: "Attributed", theme: "智慧" },
  { quote: "Attack is the secret of defense; defense is the planning of an attack.", author: "Sun Tzu", source: "《The Art of War》", theme: "智慧" },
  { quote: "Know yourself and you will win all battles.", author: "Sun Tzu", source: "《The Art of War》", theme: "智慧" },
  { quote: "In the midst of chaos, there is also opportunity.", author: "Sun Tzu", source: "《The Art of War》", theme: "智慧" },
  { quote: "The supreme art of war is to subdue the enemy without fighting.", author: "Sun Tzu", source: "《The Art of War》", theme: "智慧" },
  { quote: "Strategy without tactics is the slowest route to victory. Tactics without strategy is the noise before defeat.", author: "Sun Tzu", source: "《The Art of War》", theme: "智慧" },
  { quote: "Let your plans be dark and impenetrable as night, and when you move, like thunder you will bring lightning.", author: "Sun Tzu", source: "《The Art of War》", theme: "智慧" },
  { quote: "He wins his battles by making no mistakes. Making no mistakes is what establishes the certainty of victory.", author: "Sun Tzu", source: "《The Art of War》", theme: "智慧" },
  { quote: "One may know how to conquer without being able to do it.", author: "Sun Tzu", source: "《The Art of War》", theme: "智慧" },,
  { quote: "愿中国青年都摆脱冷气，只是向上走，不必听自暴自弃者流的话。", author: "鲁迅", source: "《热风》", theme: "励志" },
  { quote: "希望是附丽于存在的，有存在，便有希望，有希望，便是光明。", author: "鲁迅", source: "《狂人日记》", theme: "励志" },
  { quote: "真的猛士，敢于直面惨淡的人生，敢于正视淋漓的鲜血。", author: "鲁迅", source: "《纪念刘和珍君》", theme: "励志" },
  { quote: "横眉冷对千夫指，俯首甘为孺子牛。", author: "鲁迅", source: "《自嘲》", theme: "智慧" },
  { quote: "世上本没有路，走的人多了，也便成了路。", author: "鲁迅", source: "《故乡》", theme: "智慧" },
  { quote: "时间就像海绵里的水，只要愿挤，总还是有的。", author: "鲁迅", source: "《鲁迅箴言》", theme: "智慧" },
  { quote: "不在沉默中爆发，就在沉默中灭亡。", author: "鲁迅", source: "《纪念刘和珍君》", theme: "励志" },
  { quote: "哀其不幸，怒其不争。", author: "鲁迅", source: "《孔乙己》", theme: "智慧" },
  { quote: "让死的水腐下去，让活的水沸腾起来。", author: "鲁迅", source: "《华盖集》", theme: "励志" },
  { quote: "人类的悲欢并不相通，我只觉得他们吵闹。", author: "鲁迅", source: "《而已集》", theme: "智慧" },
  { quote: "当我沉默的时候，我觉得充实；我将开口，同时感到空虚。", author: "鲁迅", source: "《野草》", theme: "智慧" },
  { quote: "改造自己，总比禁止别人来得难。", author: "鲁迅", source: "《且介亭杂文》", theme: "智慧" },
  { quote: "一个没有英雄的民族是可悲的民族，一个有英雄却不知敬重爱惜的民族是不可救药的民族。", author: "鲁迅", source: "《鲁迅杂文》", theme: "智慧" },
  { quote: "生命是我自己的东西，所以我不妨大步走去，向着我以为可以走去的路。", author: "鲁迅", source: "《华盖集》", theme: "励志" },
  { quote: "贪安稳就没有自由，要自由就总要历些危险。", author: "鲁迅", source: "《老调子已经唱完》", theme: "励志" },
  { quote: "Knowledge is power.", author: "Francis Bacon", source: "《Meditationes Sacrae》", theme: "智慧" },
  { quote: "Reading makes a full man; conference a ready man; and writing an exact man.", author: "Francis Bacon", source: "《Of Studies》", theme: "智慧" },
  { quote: "Some books are to be tasted, others to be swallowed, and some few to be chewed and digested.", author: "Francis Bacon", source: "《Of Studies》", theme: "智慧" },
  { quote: "A wise man will make more opportunities than he finds.", author: "Francis Bacon", source: "《OfBoldness》", theme: "智慧" },
  { quote: "If a man will begin with certainties, he shall end in doubts; but if he will be content to begin with doubts, he shall end in certainties.", author: "Francis Bacon", source: "《The Advancement of Learning》", theme: "智慧" },
  { quote: "The greatest virtue of man is to petition God for others and to compassionate the distressed.", author: "Francis Bacon", source: "《Essays》", theme: "智慧" },
  { quote: "He that gives good advice, builds with one hand; he that gives good counsel and example, builds with both.", author: "Francis Bacon", source: "《Essays》", theme: "智慧" },
  { quote: "Nature is gentle, and if she be left alone, she is more powerful than art.", author: "Francis Bacon", source: "《The Natural History》", theme: "智慧" },
  { quote: "Choose the most beneficial thing, not the most noble.", author: "Francis Bacon", source: "《Essays》", theme: "智慧" },
  { quote: "Was mich nicht umbringt, macht mich stärker.", author: "Friedrich Nietzsche", source: "《Götzen-Dämmerung》", theme: "励志" },
  { quote: "Man muss noch Chaos in sich haben, um einen tanzenden Stern gebären zu können.", author: "Friedrich Nietzsche", source: "《Also Sprach Zarathustra》", theme: "励志" },
  { quote: "Was du ererbt von deinen Vätern, musst du erwerben, um es zu besitzen.", author: "Friedrich Nietzsche", source: "《Also Sprach Zarathustra》", theme: "励志" },
  { quote: "Der Mensch ist ein Seil, geknüpft zwischen Tier und Übermensch – ein Seil über einem Abgrund.", author: "Friedrich Nietzsche", source: "《Also Sprach Zarathustra》", theme: "智慧" },
  { quote: "Es gibt immer irgendwo einen Ausgang aus der Krankheit heraus.", author: "Friedrich Nietzsche", source: "《Ecce Homo》", theme: "励志" },
  { quote: "There are no beautiful surfaces without a terrible depth.", author: "Friedrich Nietzsche", source: "《Beyond Good and Evil》", theme: "智慧" },
  { quote: "The higher we soar, the smaller we appear to those who cannot fly.", author: "Friedrich Nietzsche", source: "《Thus Spoke Zarathustra》", theme: "智慧" },
  { quote: "No one can construct for you the bridge upon which precisely you must cross the stream of life.", author: "Friedrich Nietzsche", source: "《Schopenhauer as Educator》", theme: "智慧" },
  { quote: "Es ist nicht genug, zu wissen — man muss auch anwenden; es ist nicht genug, zu wollen — man muss auch tun.", author: "Johann Wolfgang von Goethe", source: "《Wilhelm Meister》", theme: "智慧" },
  { quote: "Handle so, dass die Maxime deines Willens jederzeit zugleich als Prinzip einer allgemeinen Gesetzgebung gelten könnte.", author: "Immanuel Kant", source: "《Grundlegung zur Metaphysik der Sitten》", theme: "智慧" },
  { quote: "Wer immer tut, was er schon kann, bleibt stets, was er schon ist.", author: "Johann Wolfgang von Goethe", source: "《Maximen und Reflexionen》", theme: "励志" },
  { quote: "Die beste Vorbereitung auf gute Arbeit ist gute Arbeit.", author: "Johann Wolfgang von Goethe", source: "《Maximen und Reflexionen》", theme: "励志" },
  { quote: "Es ist nicht die Aufgabe zu sehen, was noch niemand gesehen hat, sondern zu denken, was noch niemand gedacht hat.", author: "Johann Wolfgang von Goethe", source: "《Maximen und Reflexionen》", theme: "智慧" },
  { quote: "Mut ist die dispensable quality of a hero.", author: "Johann Wolfgang von Goethe", source: "《Iphigenie auf Tauris》", theme: "励志" },
  { quote: "Nothing is worth as much as this day.", author: "Johann Wolfgang von Goethe", source: "《Faust》", theme: "智慧" },
  { quote: "A man can fail many times, but he isn't a failure until he begins to blame somebody else.", author: "Johann Wolfgang von Goethe", source: "《Attributed》", theme: "励志" },
  { quote: "The soul that sees beauty may sometimes walk alone.", author: "Johann Wolfgang von Goethe", source: "《Wilhelm Meister》", theme: "智慧" },
  { quote: "We suffer more often in imagination than in reality.", author: "Seneca", source: "《Letters from a Stoic》", theme: "智慧" },
  { quote: "Luck is what happens when preparation meets opportunity.", author: "Seneca", source: "《Letters from a Stoic》", theme: "智慧" },
  { quote: "It is not that we have a short time to live, but that we waste a lot of it.", author: "Seneca", source: "《On the Shortness of Life》", theme: "智慧" },
  { quote: "Difficulties strengthen the mind, as labor does the body.", author: "Seneca", source: "《Moral Letters to Lucilius》", theme: "励志" },
  { quote: "As is a tale, so is life: not how long it is, but how good it is, is what matters.", author: "Seneca", source: "《Letters from a Stoic》", theme: "智慧" },
  { quote: "Sometimes even to live is an act of courage.", author: "Seneca", source: "《Letters from a Stoic》", theme: "励志" },
  { quote: "He who is brave is free.", author: "Seneca", source: "《Letters from a Stoic》", theme: "励志" },
  { quote: "True happiness is to enjoy the present, without anxious dependence upon the future.", author: "Seneca", source: "《Letters from a Stoic》", theme: "智慧" },
  { quote: "The whole future lies in uncertainty: live immediately.", author: "Seneca", source: "《Letters from a Stoic》", theme: "励志" },
  { quote: "No man is free who is not master of himself.", author: "Seneca", source: "《Attributed》", theme: "智慧" },
  { quote: "The unexamined life is not worth living.", author: "Socrates", source: "Plato's Apology", theme: "智慧" },
  { quote: "I know that I know nothing.", author: "Socrates", source: "Plato's Dialogues", theme: "智慧" },
  { quote: "Education is the kindling of a flame, not the filling of a vessel.", author: "Socrates", source: "Attributed", theme: "智慧" },
  { quote: "Strong minds discuss ideas, average minds discuss events, weak minds discuss people.", author: "Socrates", source: "Attributed", theme: "智慧" },
  { quote: "Be kind, for everyone you meet is fighting a hard battle.", author: "Socrates", source: "Attributed", theme: "智慧" },
  { quote: "To find yourself, think for yourself.", author: "Socrates", source: "Attributed", theme: "智慧" },
  { quote: "The only true wisdom is in knowing you know nothing.", author: "Socrates", source: "Attributed", theme: "智慧" },
  { quote: "知是行的开始，行是知的完成。知而不行，等于不知。", author: "王阳明", source: "《传习录》", theme: "智慧" },
  { quote: "破山中之贼易，破心中之贼难。", author: "王阳明", source: "《与杨仕德薛尚谦书》", theme: "智慧" },
  { quote: "此心不动，随机而动。", author: "王阳明", source: "《传习录》", theme: "智慧" },
  { quote: "人须在事上磨，方能立得住；方能静亦定、动亦定。", author: "王阳明", source: "《传习录》", theme: "智慧" },
  { quote: "无善无恶心之体，有善有恶意之动。知善知恶是良知，为善去恶是格物。", author: "王阳明", source: "《传习录》", theme: "智慧" },
  { quote: "志不立，天下无可成之事。", author: "王阳明", source: "《教条示龙场诸生》", theme: "励志" },
  { quote: "知行合一，方是真知。", author: "王阳明", source: "《传习录》", theme: "智慧" },
  { quote: "减得一分人欲，便是复得一分天理。", author: "王阳明", source: "《传习录》", theme: "智慧" },
  { quote: "越是艰难处，越是修心时。", author: "王阳明", source: "《传习录》", theme: "励志" },
  { quote: "人皆知有用之用，而莫知无用之用也。", author: "庄子", source: "《人间世》", theme: "智慧" },
  { quote: "无用之用，是为大用。", author: "庄子", source: "《人间世》", theme: "智慧" },
  { quote: "相濡以沫，不如相忘于江湖。", author: "庄子", source: "《大宗师》", theme: "智慧" },
  { quote: "井蛙不可以语于海者，拘于虚也；夏虫不可以语于冰者，笃于时也。", author: "庄子", source: "《秋水》", theme: "智慧" },
  { quote: "天地与我并生，而万物与我为一。", author: "庄子", source: "《齐物论》", theme: "智慧" },
  { quote: "君子之交淡若水，小人之交甘若醴。", author: "庄子", source: "《山木》", theme: "智慧" },
  { quote: "吾生也有涯，而知也无涯。以有涯随无涯，殆已。", author: "庄子", source: "《养生主》", theme: "智慧" },
  { quote: "至乐无乐，至誉无誉。", author: "庄子", source: "《至乐》", theme: "智慧" },
  { quote: "举世而誉之而不加劝，举世而非之而不加沮。", author: "庄子", source: "《逍遥游》", theme: "智慧" },
  { quote: "知人者智，自知者明。", author: "老子", source: "《道德经》", theme: "智慧" },
  { quote: "胜人者有力，自胜者强。", author: "老子", source: "《道德经》", theme: "智慧" },
  { quote: "祸兮，福之所倚；福兮，祸之所伏。", author: "老子", source: "《道德经》", theme: "智慧" },
  { quote: "上善若水，水善利万物而不争。", author: "老子", source: "《道德经》", theme: "智慧" },
  { quote: "以其不争，故天下莫能与之争。", author: "老子", source: "《道德经》", theme: "智慧" },
  { quote: "合抱之木，生于毫末；九层之台，起于累土。", author: "老子", source: "《道德经》", theme: "智慧" },
  { quote: "信言不美，美言不信。", author: "老子", source: "《道德经》", theme: "智慧" },
  { quote: "知足者富，强行者有志。", author: "老子", source: "《道德经》", theme: "智慧" },
  { quote: "为学日益，为道日损。", author: "老子", source: "《道德经》", theme: "智慧" },
  { quote: "问渠那得清如许，为有源头活水来。", author: "朱熹", source: "《观书有感》", theme: "智慧" },
  { quote: "读书有三到，谓心到、眼到、口到。", author: "朱熹", source: "《训学斋规》", theme: "智慧" },
  { quote: "循序而渐进，熟读而精思。", author: "朱熹", source: "《读书之要》", theme: "智慧" },
  { quote: "少年易老学难成，一寸光阴不可轻。", author: "朱熹", source: "《偶成》", theme: "励志" },
  { quote: "格物致知，诚意正心。", author: "朱熹", source: "《大学章句》", theme: "智慧" },
  { quote: "涵养为首，致知次之，力行又次之。", author: "朱熹", source: "《朱子语类》", theme: "智慧" },
  { quote: "一个人彻悟的程度，恰等于他所受痛苦的深度。", author: "林语堂", source: "《吾国与吾民》", theme: "智慧" },
  { quote: "人生不过如此，且行且珍惜。自己永远是自己的主角，不要总在别人的戏剧里充当着配角。", author: "林语堂", source: "《人生不过如此》", theme: "智慧" },
  { quote: "幸福无非四件事：一是睡在自家床上，二是吃父母做的菜，三是听爱人讲情话，四是跟孩子做游戏。", author: "林语堂", source: "《人生不过如此》", theme: "智慧" },
  { quote: "我们最重要的不是去计较真与伪，得与失，名与利，贵与贱，贫与富，而是如何好好地快乐度日。", author: "林语堂", source: "《生活的艺术》", theme: "智慧" },
  { quote: "人要有着落，有寄托，才是人生。", author: "林语堂", source: "《京华烟云》", theme: "智慧" },
  { quote: "岁月不饶人，我亦未曾饶过岁月。", author: "木心", source: "《云雀叫了一整天》", theme: "励志" },
  { quote: "所谓无底深渊，下去，也是前程万里。", author: "木心", source: "《素履之往》", theme: "励志" },
  { quote: "我追索人心的深度，却看见了人心的浅薄。", author: "木心", source: "《云雀叫了一整天》", theme: "智慧" },
  { quote: "从前车马很慢，书信很远，一生只够爱一个人。", author: "木心", source: "《从前慢》", theme: "爱情" },
  { quote: "人类的地狱都是自己造成的。", author: "木心", source: "《文学回忆录》", theme: "智慧" },
  { quote: "艺术的生命良心，不是快乐，是安慰。", author: "木心", source: "《文学回忆录》", theme: "智慧" },
  { quote: "悲观是一种远见，鼠目寸光的人，不容易悲观。", author: "木心", source: "《文学回忆录》", theme: "智慧" },
  { quote: "知识是引出智慧的光，没有光，世界就是黑暗的。", author: "木心", source: "《文学回忆录》", theme: "智慧" },
  { quote: "世界上只有一种真正的英雄主义，那就是在认清生活的真相后依然热爱生活。", author: "Romain Rolland", source: "《米开朗琪罗传》", theme: "励志" },
  { quote: "La vie n'est pas un combat mais une chanson. / 生活中唯一的战斗，就是不断前进。", author: "Romain Rolland", source: "《约翰·克利斯朵夫》", theme: "励志" },
  { quote: "Nothing is more precious than independence and freedom.", author: "Romain Rolland", source: "《Attributed》", theme: "智慧" },
  { quote: "A really great man is known by the fact that he humbles himself to no one.", author: "Romain Rolland", source: "《Attributed》", theme: "智慧" },
  { quote: "La碧玺的唯一意义是行动。", author: "Romain Rolland", source: "《Attributed》", theme: "励志" },
  { quote: "Life这把武器，你要用它来做什么？用来创造美，不是用来毁灭。", author: "Romain Rolland", source: "《Attributed》", theme: "励志" },
  { quote: "Three passions, simple but overwhelmingly strong, have governed my life: the longing for love, the search for knowledge.", author: "Bertrand Russell", source: "《A Russell's Autobiography》", theme: "智慧" },
  { quote: "The good life is one inspired by love and guided by knowledge.", author: "Bertrand Russell", source: "《Attributed》", theme: "智慧" },
  { quote: "Do not fear to be eccentric in opinion, for every opinion now accepted was once eccentric.", author: "Bertrand Russell", source: "《Attributed》", theme: "智慧" },
  { quote: "The fundamental cause of trouble in the world today is that the stupid are cocksure while the intelligent are full of doubt.", author: "Bertrand Russell", source: "《Attributed》", theme: "智慧" },
  { quote: "To conquer fear is the beginning of wisdom.", author: "Bertrand Russell", source: "《Attributed》", theme: "智慧" },
  { quote: "War does not determine who is right — only who is left.", author: "Bertrand Russell", source: "《Attributed》", theme: "智慧" },
  { quote: "Life isn't about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw", source: "《Attributed》", theme: "励志" },
  { quote: "A life spent making mistakes is not only more honorable, but more useful, than a life spent doing nothing.", author: "George Bernard Shaw", source: "《Attributed》", theme: "励志" },
  { quote: "People who say it cannot be done should not interrupt those who are doing it.", author: "George Bernard Shaw", source: "《Attributed》", theme: "智慧" },
  { quote: "Imagination is the beginning of creation.", author: "George Bernard Shaw", source: "《Attributed》", theme: "智慧" },
  { quote: "The single biggest problem in communication is the illusion that it has taken place.", author: "George Bernard Shaw", source: "《Attributed》", theme: "智慧" },
  { quote: "If you want to be successful, start thinking of yourself as a success.", author: "John D. Rockefeller", source: "《Attributed》", theme: "励志" },
  { quote: "The secret of success is to do the common thing uncommonly well.", author: "John D. Rockefeller", source: "《Attributed》", theme: "智慧" },
  { quote: "I have no secret of success but hard work.", author: "John D. Rockefeller", source: "《Attributed》", theme: "励志" },
  { quote: "If your only goal is to become rich, you will never achieve it.", author: "John D. Rockefeller", source: "《Attributed》", theme: "智慧" },
  { quote: "Next to doing the right thing, the most important thing is to let people know you are doing the right thing.", author: "John D. Rockefeller", source: "《Attributed》", theme: "智慧" },
  { quote: "人生·工作的结果＝思维方式×热情×能力。", author: "稻盛和夫", source: "《活法》", theme: "智慧" },
  { quote: "坚持\"燃烧的斗魂\"，抱着纯粹而强烈的愿望，不懈地努力。", author: "稻盛和夫", source: "《活法》", theme: "励志" },
  { quote: "不要怕走弯路，重要的是你走的方向是否正确。", author: "稻盛和夫", source: "《活法》", theme: "智慧" },
  { quote: "每天的工作都需要全力以赴，每一天的积累就是一年，一年的积累就是一生。", author: "稻盛和夫", source: "《活法》", theme: "励志" },
  { quote: "积善行、思利他，就能领悟宇宙的法则，离幸福更近。", author: "稻盛和夫", source: "《活法》", theme: "智慧" },
  { quote: "乐观地设想，悲观地计划，愉快地执行。", author: "稻盛和夫", source: "《活法》", theme: "智慧" },
  { quote: "苟利国家生死以，岂因祸福避趋之。", author: "林则徐", source: "《赴戍登程口占示家人》", theme: "励志" },
  { quote: "海纳百川，有容乃大；壁立千仞，无欲则刚。", author: "林则徐", source: "自题联", theme: "智慧" },
  { quote: "若鸦片一日不绝，本大臣一日不回。", author: "林则徐", source: "《林则徐集》", theme: "励志" },
  { quote: "天下古今之庸人，皆以一惰字致败；天下古今之才人，皆以一傲字致败。", author: "曾国藩", source: "《曾国藩家书》", theme: "智慧" },
  { quote: "既往不恋，当下不杂，未来不迎。", author: "曾国藩", source: "《曾国藩家书》", theme: "智慧" },
  { quote: "坚其志，苦其心，劳其力，事无大小，必有所成。", author: "曾国藩", source: "《曾国藩家书》", theme: "励志" },
  { quote: "天可补，海可填，南山可移。日月既往，不可复追。", author: "曾国藩", source: "《曾国藩家书》", theme: "智慧" },
  { quote: "家俭则兴，人勤则健；能勤能俭，永不贫贱。", author: "曾国藩", source: "《曾国藩家书》", theme: "智慧" },
  { quote: "唯天下之至诚能胜天下之至伪；唯天下之至拙能胜天下之至巧。", author: "曾国藩", source: "《曾国藩家书》", theme: "智慧" },
  { quote: "眼睛仅盯在自己小口袋的是小商人，眼光放在全世界的是大商人。", author: "李嘉诚", source: "《Attributed》", theme: "智慧" },
  { quote: "栽种思想成就行为，栽种行为成就习惯，栽种习惯成就性格，栽种性格成就命运。", author: "李嘉诚", source: "《Attributed》", theme: "智慧" },
  { quote: "发光并非太阳的专利，你也可以发光。", author: "李嘉诚", source: "《Attributed》", theme: "励志" },
  { quote: "知识是通往成功的阶梯，但谦虚是通向知识的第一步。", author: "李嘉诚", source: "《Attributed》", theme: "智慧" },
  { quote: "Success is a lousy teacher. It seduces smart people into thinking they can't lose.", author: "Bill Gates", source: "《Attributed》", theme: "智慧" },
  { quote: "Your most unhappy customers are your greatest source of learning.", author: "Bill Gates", source: "《Attributed》", theme: "智慧" },
  { quote: "It's fine to celebrate success but it is more important to heed the lessons of failure.", author: "Bill Gates", source: "《Attributed》", theme: "智慧" },
  { quote: "If you are born poor it's not your mistake, but if you die poor it is your mistake.", author: "Bill Gates", source: "《Attributed》", theme: "励志" },
  { quote: "We all need people who will give us feedback. That's how we improve.", author: "Bill Gates", source: "《Attributed》", theme: "智慧" },
  { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey", source: "《Attributed》", theme: "励志" },
  { quote: "The biggest adventure you can take is to live the life of your dreams.", author: "Oprah Winfrey", source: "《Attributed》", theme: "励志" },
  { quote: "You can have it all. You just can't have it all at once.", author: "Oprah Winfrey", source: "《Attributed》", theme: "智慧" },
  { quote: "Doing the best at this moment puts you in the best place for the next moment.", author: "Oprah Winfrey", source: "《Attributed》", theme: "智慧" },
  { quote: "Be thankful for what you have; you'll end up having more.", author: "Oprah Winfrey", source: "《Attributed》", theme: "智慧" },
  { quote: "The people who are crazy enough to think they can change the world are the ones who do.", author: "Steve Jobs", source: "Apple Think Different campaign", theme: "励志" },
  { quote: "Stay hungry, stay foolish.", author: "Steve Jobs", source: "Stanford Commencement Speech 2005", theme: "励志" },
  { quote: "Design is not just what it looks like and feels like. Design is how it works.", author: "Steve Jobs", source: "《Attributed》", theme: "智慧" },
  { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs", source: "Stanford Commencement Speech 2005", theme: "励志" },
  { quote: "We can do what we wish, but we can only wish what we are.", author: "Arthur Schopenhauer", source: "《Attributed》", theme: "智慧" },
  { quote: "The world is my representation.", author: "Arthur Schopenhauer", source: "《The World as Will and Representation》", theme: "智慧" },
  { quote: "A man can be himself only so long as he is alone.", author: "Arthur Schopenhauer", source: "《Attributed》", theme: "智慧" },
  { quote: "Pain is the positive element in life; pleasure is the negative.", author: "Arthur Schopenhauer", source: "《Attributed》", theme: "智慧" },
  { quote: "To live is to suffer; to survive is to find meaning in the suffering.", author: "Arthur Schopenhauer", source: "《Attributed》", theme: "智慧" },
  { quote: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", source: "《Nicomachean Ethics》", theme: "智慧" },
  { quote: "Patience is bitter, but its fruit is sweet.", author: "Aristotle", source: "《Attributed》", theme: "励志" },
  { quote: "Quality is not an act, it is a habit.", author: "Aristotle", source: "《Attributed》", theme: "励志" },
  { quote: "The educated differ from the uneducated as much as the living differ from the dead.", author: "Aristotle", source: "《Attributed》", theme: "智慧" },
  { quote: "Hope is a waking dream.", author: "Aristotle", source: "《Attributed》", theme: "智慧" },
  { quote: "The energy of the mind is the essence of life.", author: "Aristotle", source: "《Attributed》", theme: "智慧" },
  { quote: "Every act of kindness has some healing power of its own.", author: "John J. Hugh", source: "《Attributed》", theme: "智慧" },
  { quote: "The art of being wise is the art of knowing what to overlook.", author: "William James", source: "《Attributed》", theme: "智慧" },
  { quote: "Act only according to that maxim whereby you can at the same time will that it should become a universal law.", author: "Immanuel Kant", source: "《Groundwork of the Metaphysics of Morals》", theme: "智慧" },
  { quote: "Happiness is not an ideal of reason, but of imagination.", author: "Immanuel Kant", source: "《Attributed》", theme: "智慧" },
  { quote: "We must also think of others, for we do not live alone.", author: "Maria Montessori", source: "《Attributed》", theme: "智慧" },
  { quote: "Free these little children. Let them run in the fields, breathe the pure air, and grow strong and healthy.", author: "Maria Montessori", source: "《Attributed》", theme: "智慧" },
  { quote: "Success is getting what you want. Happiness is wanting what you get.", author: "Dale Carnegie", source: "《Attributed》", theme: "智慧" },
  { quote: "The most important thing in communication is hearing what isn't said.", author: "Peter Drucker", source: "《Attributed》", theme: "智慧" },
  { quote: "Laziness is nothing more than the habit of resting before you get tired.", author: "Jules Renard", source: "《Attributed》", theme: "励志" },
  { quote: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman", source: "《Attributed》", theme: "励志" },
  { quote: "Darkness cannot drive out darkness; only light can do that.", author: "Martin Luther King Jr.", source: "《Attributed》", theme: "智慧" },
  { quote: "The time is always right to do what is right.", author: "Martin Luther King Jr.", source: "《Attributed》", theme: "智慧" },
  { quote: "Injustice anywhere is a threat to justice everywhere.", author: "Martin Luther King Jr.", source: "Letter from Birmingham Jail", theme: "智慧" },
  { quote: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr.", source: "《Attributed》", theme: "智慧" },
  { quote: "I have decided to stick with love. Hate is too great a burden to bear.", author: "Martin Luther King Jr.", source: "《Attributed》", theme: "智慧" },
  { quote: "Intelligence plus character—that is the goal of true education.", author: "Martin Luther King Jr.", source: "《Attributed》", theme: "智慧" },
  { quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela", source: "《Attributed》", theme: "励志" },
  { quote: "It always seems impossible until it's done.", author: "Nelson Mandela", source: "《Attributed》", theme: "励志" },
  { quote: "I learned that courage was not the absence of fear, but the triumph over it.", author: "Nelson Mandela", source: "《Attributed》", theme: "励志" },
  { quote: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela", source: "Speech, 1990", theme: "励志" },
  { quote: "A winner is a dreamer who never gives up.", author: "Nelson Mandela", source: "《Attributed》", theme: "励志" },
  { quote: "Nothing is impossible, the word itself says 'I'm possible'!", author: "Audrey Hepburn", source: "《Attributed》", theme: "励志" },
  { quote: "You can have results or excuses, not both.", author: "Conor McGregor", source: "《Attributed》", theme: "励志" },
  { quote: "I am not what happened to me. I am what I choose to become.", author: "Carl Jung", source: "《Attributed》", theme: "励志" },
  { quote: "Until you make the unconscious conscious, it will direct your life and you will call it fate.", author: "Carl Jung", source: "《Attributed》", theme: "智慧" },
  { quote: "Everything that irritates us about others can lead us to an understanding of ourselves.", author: "Carl Jung", source: "《Attributed》", theme: "智慧" },
  { quote: "种一棵树最好的时间是十年前，其次是现在。", author: "中国谚语", source: "谚语", theme: "励志" },
  { quote: "书山有路勤为径，学海无涯苦作舟。", author: "韩愈", source: "《增广贤文》", theme: "励志" },
  { quote: "千里之堤，毁于蚁穴。", author: "韩非子", source: "《韩非子》", theme: "智慧" },
  { quote: "当局者迷，旁观者清。", author: "沈括", source: "《梦溪笔谈》", theme: "智慧" },
  { quote: "人有悲欢离合，月有阴晴圆缺。", author: "苏轼", source: "《水调歌头》", theme: "智慧" },
  { quote: "但愿人长久，千里共婵娟。", author: "苏轼", source: "《水调歌头》", theme: "爱情" },
  { quote: "回首向来萧瑟处，归去，也无风雨也无晴。", author: "苏轼", source: "《定风波》", theme: "智慧" },
  { quote: "十年生死两茫茫，不思量，自难忘。", author: "苏轼", source: "《江城子》", theme: "爱情" },
  { quote: "人生如逆旅，我亦是行人。", author: "苏轼", source: "《临江仙》", theme: "智慧" },
  { quote: "腹有诗书气自华，读书万卷始通神。", author: "苏轼", source: "《和董传留别》", theme: "励志" },
  { quote: "世事洞明皆学问，人情练达即文章。", author: "曹雪芹", source: "《红楼梦》", theme: "智慧" },
  { quote: "身后有余忘缩手，眼前无路想回头。", author: "曹雪芹", source: "《红楼梦》", theme: "智慧" },
  { quote: "满纸荒唐言，一把辛酸泪。", author: "曹雪芹", source: "《红楼梦》", theme: "智慧" },
  { quote: "滴不尽相思血泪抛红豆，开不完春柳春花满画楼。", author: "曹雪芹", source: "《红楼梦》", theme: "爱情" },
  { quote: "把每一个黎明看作是生命的开始，把每一个黄昏看作是你生命的小结。", author: "约翰·罗斯金", source: "《Attributed》", theme: "智慧" },
  { quote: "不要等待机会，而要创造机会。", author: "乔治·萧伯纳", source: "《Attributed》", theme: "励志" },
  { quote: "你所以感到巨人高不可攀，那是因为你跪着。", author: "马克思", source: "《Attributed》", theme: "励志" },
  { quote: "当你以为门关上了的时候，其实它是开着的。", author: "保罗·柯艾略", source: "《牧羊少年奇幻之旅》", theme: "智慧" },
  { quote: "当你真心渴望某样东西时，整个宇宙都会来帮你。", author: "保罗·柯艾略", source: "《牧羊少年奇幻之旅》", theme: "智慧" },
  { quote: "If you want to achieve greatness stop asking for permission.", author: "Anonymous", source: "Attributed", theme: "励志" },
  { quote: "Don't count the days, make the days count.", author: "Muhammad Ali", source: "Attributed", theme: "励志" },
  { quote: "I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'", author: "Muhammad Ali", source: "Attributed", theme: "励志" },
  { quote: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Muhammad Ali", source: "Attributed", theme: "励志" },
  { quote: "If you always do what you have always done, you will always get what you have always gotten.", author: "Tony Robbins", source: "Attributed", theme: "励志" },
  { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt", source: "Attributed", theme: "励志" },
  { quote: "A positive attitude causes a chain reaction of positive thoughts, events and outcomes.", author: "Wade Boggs", source: "Attributed", theme: "励志" },
  { quote: "It is not the load that breaks you down, it's the way you carry it.", author: "Lena Horne", source: "Attributed", theme: "智慧" },
  { quote: "Every day may not be good, but there is something good in every day.", author: "Alice Morse Earle", source: "Attributed", theme: "智慧" },
  { quote: "Be the energy you want to attract.", author: "Unknown", source: "Attributed", theme: "智慧" },
  { quote: "What you seek is seeking you.", author: "Rumi", source: "Attributed", theme: "智慧" },
  { quote: "The wound is the place where the Light enters you.", author: "Rumi", source: "Attributed", theme: "智慧" },
  { quote: "Let yourself be silently drawn by the strange pull of what you really love. It will not lead you astray.", author: "Rumi", source: "Attributed", theme: "智慧" },
  { quote: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", author: "Rumi", source: "Attributed", theme: "智慧" },
  { quote: "Set your life on fire. Seek those who fan your flames.", author: "Rumi", source: "Attributed", theme: "励志" },
  { quote: "The art of knowing is knowing what to ignore.", author: "Rumi", source: "Attributed", theme: "智慧" },
  { quote: "Accept loss forever. Accept loss in your heart, and you will begin to find strength within.", author: "Miyamoto Musashi", source: "《The Book of Five Rings》", theme: "智慧" },
  { quote: "Think lightly of yourself and deeply of the world.", author: "Miyamoto Musashi", source: "《The Book of Five Rings》", theme: "智慧" },
  { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", source: "Attributed", theme: "励志" },
  { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt", source: "Attributed", theme: "励志" },
  { quote: "Courage is not having the strength to go on; it is going on when you don't have the strength.", author: "Theodore Roosevelt", source: "Attributed", theme: "励志" },
  { quote: "Nothing in the world is worth having or worth doing unless it means effort, pain, difficulty.", author: "Theodore Roosevelt", source: "Attributed", theme: "励志" },
  { quote: "It is not the critic who counts; not the man who points out how the strong man stumbled.", author: "Theodore Roosevelt", source: "《Citizenship in a Republic》", theme: "励志" },
  { quote: "Life is what happens when you're busy making other plans.", author: "John Lennon", source: "《Beautiful Boy》", theme: "智慧" },
  { quote: "Better to light one small candle than to curse the darkness.", author: "Chinese Proverb", source: "Proverb", theme: "励志" },
  { quote: "He who conquers himself is the mightiest warrior.", author: "Confucius", source: "Attributed", theme: "智慧" },
  { quote: "Real knowledge is to know the extent of one's ignorance.", author: "Confucius", source: "Attributed", theme: "智慧" },
  { quote: "Respect yourself and others will respect you.", author: "Confucius", source: "Attributed", theme: "智慧" },
  { quote: "Fall seven times, stand up eight.", author: "Japanese Proverb", source: "Proverb", theme: "励志" },
  { quote: "No matter how long the rain lasts, there will never be any true cold without hope.", author: "Dan Zadra", source: "Attributed", theme: "励志" },
  { quote: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett", source: "《The Light in the Heart》", theme: "励志" },
  { quote: "Be brave. Take risks. Nobody can touch you. You are the only master of your own destiny.", author: "Anita K. Booth", source: "Attributed", theme: "励志" },
  { quote: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand", source: "Attributed", theme: "励志" },
  { quote: "The person who says it cannot be done should not interrupt the person who is doing it.", author: "Chinese Proverb", source: "Proverb", theme: "励志" },
  { quote: "He who asks is a fool for five minutes, but he who does not ask remains a fool forever.", author: "Chinese Proverb", source: "Proverb", theme: "智慧" },
  { quote: "Give a man a fish and you feed him for a day. Teach him how to fish and you feed him for a lifetime.", author: "Chinese Proverb", source: "Proverb", theme: "智慧" },
  { quote: "To see what is right and not do it is the want of courage.", author: "Confucius", source: "Attributed", theme: "智慧" },
  { quote: "Learn as if you were to live forever.", author: "Mahatma Gandhi", source: "Attributed", theme: "励志" },
  { quote: "You must not lose faith in humanity. Humanity is an ocean; if a few drops of the ocean are dirty, the ocean does not become dirty.", author: "Mahatma Gandhi", source: "Attributed", theme: "智慧" },
  { quote: "An eye for an eye only ends up making the whole world blind.", author: "Mahatma Gandhi", source: "Attributed", theme: "智慧" },
  { quote: "First they ignore you, then they laugh at you, then they fight you, then you win.", author: "Mahatma Gandhi", source: "Attributed", theme: "励志" },
  { quote: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi", source: "Attributed", theme: "智慧" },
  { quote: "No one who brags is brave. No one who is brave brags.", author: "古罗马谚语", source: "谚语", theme: "智慧" },
  { quote: "The best way to predict the future is to create it.", author: "Peter Drucker", source: "Attributed", theme: "励志" },
  { quote: "The most dangerous enemy of a better solution is a brilliant answer to an incorrect problem.", author: "Paul R. Lawrence", source: "《Attributed》", theme: "智慧" },
  { quote: "Never go to bed angry. Stay up and fight.", author: "Phyllis Bottome", source: "《Attributed》", theme: "智慧" },
  { quote: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson", source: "《Attributed》", theme: "励志" },
  { quote: "Excellence is not a destination but a continuous journey that never ends.", author: "Brian Tracy", source: "《Attributed》", theme: "励志" },
  { quote: "We generate fears while we sit. We overcome them by action.", author: "Dr. Henry Link", source: "《Attributed》", theme: "励志" },
  { quote: "A person who never made a mistake never tried anything new.", author: "Albert Einstein", source: "《Attributed》", theme: "智慧" },
  { quote: "Life is like riding a bicycle. To keep your balance you must keep moving.", author: "Albert Einstein", source: "Letter to son, 1930", theme: "智慧" },
  { quote: "Try not to become a man of success. Rather become a man of value.", author: "Albert Einstein", source: "《Attributed》", theme: "智慧" },
  { quote: "Once we accept our limits, we go beyond them.", author: "Albert Einstein", source: "《Attributed》", theme: "励志" },
  { quote: "The only thing that interferes with my learning is my education.", author: "Albert Einstein", source: "《Attributed》", theme: "智慧" },
  { quote: "Not everything that can be counted counts, and not everything that counts can be counted.", author: "Albert Einstein", source: "《Attributed》", theme: "智慧" },
  { quote: "Weakness of attitude becomes weakness of character.", author: "Albert Einstein", source: "《Attributed》", theme: "智慧" },
  { quote: "Peace cannot be kept by force. It can only be achieved by understanding.", author: "Albert Einstein", source: "《Attributed》", theme: "智慧" },
  { quote: "If I had an hour to solve a problem I'd spend 55 minutes thinking about the problem and 5 minutes thinking about solutions.", author: "Albert Einstein", source: "《Attributed》", theme: "智慧" },
  { quote: "The world is a dangerous place, not because of those who do evil, but because of those who look on and do nothing.", author: "Albert Einstein", source: "《Attributed》", theme: "智慧" },
  { quote: "In the middle of difficulty lies opportunity.", author: "Albert Einstein", source: "《Attributed》", theme: "励志" },
  { quote: "Imagination is more important than knowledge.", author: "Albert Einstein", source: "《Attributed》", theme: "智慧" },
  { quote: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein", source: "《Attributed》", theme: "智慧" },
  { quote: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein", source: "《Attributed》", theme: "智慧" },
  { quote: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", author: "Albert Einstein", source: "《Attributed》", theme: "智慧" },
  { quote: "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.", author: "Albert Einstein", source: "《Attributed》", theme: "智慧" },
  { quote: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein", source: "《Attributed》", theme: "智慧" },
  { quote: "Never memorize something that you can look up.", author: "Albert Einstein", source: "《Attributed》", theme: "智慧" },
  { quote: "We cannot solve our problems with the same thinking we used when we created them.", author: "Albert Einstein", source: "《Attributed》", theme: "智慧" },
  { quote: "The true sign of intelligence is not knowledge but imagination.", author: "Albert Einstein", source: "《Attributed》", theme: "智慧" },
  { quote: "Only a life lived for others is a life worthwhile.", author: "Albert Einstein", source: "《Attributed》", theme: "智慧" },
  { quote: "Education is what remains after one has forgotten what one has learned in school.", author: "Albert Einstein", source: "《Attributed》", theme: "智慧" },
  { quote: "He who knows others is wise; he who knows himself is enlightened.", author: "Lao Tzu", source: "《Tao Te Ching》", theme: "智慧" },
  { quote: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu", source: "《Tao Te Ching》", theme: "智慧" },
  { quote: "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.", author: "Lao Tzu", source: "《Tao Te Ching》", theme: "智慧" },
  { quote: "When I let go of what I am, I become what I might be.", author: "Lao Tzu", source: "《Tao Te Ching》", theme: "智慧" },
  { quote: "Life is a series of natural and spontaneous changes. Don't resist them.", author: "Lao Tzu", source: "《Tao Te Ching》", theme: "智慧" },
  { quote: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu", source: "《Tao Te Ching》", theme: "励志" },
  { quote: "Watch your thoughts, they become your words.", author: "Lao Tzu", source: "《Tao Te Ching》", theme: "智慧" },
  { quote: "If you do not change direction, you may end up where you are heading.", author: "Lao Tzu", source: "《Tao Te Ching》", theme: "智慧" },
  { quote: "To attain knowledge, add things every day. To attain wisdom, remove things every day.", author: "Lao Tzu", source: "《Tao Te Ching》", theme: "智慧" },
  { quote: "The best fighter is never angry.", author: "Lao Tzu", source: "《Tao Te Ching》", theme: "智慧" },
  { quote: "An ant on the move does not bother the one who is sleeping.", author: "Lao Tzu", source: "《Tao Te Ching》", theme: "智慧" }
];
